name: 'GitHub Actions LeetCode Weekly Bot'

on:
  push:
    branches: 
      - main
  schedule:
    - cron: '18 11 * * *'

jobs:
  dk:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install requirements'
        run: pip install -r dk/requirements.txt
      - name: 'Working'
        env:
          USER: ${{ secrets.USER }}
          EMAILPASS: ${{ secrets.EMAILPASS }}
        run: python dk/yiban.py
